#!/bin/bash
#myfind
#Sam Steinfeld
#converts DEM file to a list of numbers which are stored in a new file
#input: the name of the DEM file and the name of the file the user wishes to store new list of numbers into
#output: the user specified output file with list of numbers from DEM file will be stored in current directory

file="$1" #user inputted DEM file
output="$2" #user specified output file
value=$(<$file)  #stores name of file

if [ -f $file ] #checks to see if file is found
then
IFS=$'\n| " "' GLOBIGNORE='*' command eval  'array=($(cat ./$file))' #splits DEM file by new line character and spaces and stores numbers into array
	for ((i=10; i<=${#array[@]}; i++))
	do 
		  echo "${array[$i]}" >> $output #store numbers from array into output file
	done
fi


