#!/bin/bash
#myfind
#Sam Steinfeld
#finds number of occurrences of a word in a file
#input: the name of the word the user wishes find the number of occurrences ofthe name of the ASCII text file that
#output: the number of times the word occurs

word="$1" #the word the user is checking the number of occurrences of
file="$2" #user inputted file
if [ -f $file ] #checks to see if file is found
then
	grep -o $word $file | wc -l
else
	echo
fi
